In [53]:
import pandas as pd
import numpy as np
import os
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.metrics import accuracy_score

from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold

In [37]:
%pwd

'c:\\Users\\NishantHP\\Desktop\\MLOPS PROJECT'

In [21]:
 os.chdir('c:\\Users\\NishantHP\\Desktop\\MLOPS PROJECT')

In [38]:
df=pd.read_csv('artifacts/data_ingestion/telcom.csv')

In [39]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_grp,monthly_charge,Total_services
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,No,Month-to-month,Yes,Electronic check,29.85,29.85,1,0-1yrs,low,1
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,No,One year,No,Mailed check,56.95,1889.5,1,2-3yrs,medium,3
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0-1yrs,medium,3
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,No,One year,No,Bank transfer (automatic),42.30,1840.75,1,3-4yrs,low,3
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0-1yrs,medium,1

In [24]:
df['Churn']=df['Churn'].map({'Yes':0,'No':1})

In [40]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges        Churn  Total_services
count    7043.000000  7043.000000     7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692     0.734630        3.362914
std         0.368612    24.559481       30.090047     0.441561        2.062031
min         0.000000     0.000000       18.250000     0.000000        0.000000
25%         0.000000     9.000000       35.500000     0.000000        1.000000
50%         0.000000    29.000000       70.350000     1.000000        3.000000
75%         0.000000    55.000000       89.850000     1.000000        5.000000
max         1.000000    72.000000      118.750000     1.000000        8.000000

In [41]:
df['tenure_grp']=pd.cut(df['tenure'],
                        bins=[0,12,24,36,48,60,72],
                        labels=['0-1yrs','1-2yrs','2-3yrs','3-4yrs','4-5yrs','5-6yrs'])

In [42]:
df['monthly_charge']=pd.cut(df['MonthlyCharges'],bins=3,labels=['low','medium','high'])

In [43]:
#df.drop('customerID',axis=1)

In [44]:
services = ['PhoneService', 'MultipleLines', 'InternetService',
            'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
            'TechSupport', 'StreamingTV', 'StreamingMovies']
df['Total_services']=df[services].apply(lambda x:(x=='Yes').sum() ,axis=1)

In [45]:
X=df.drop('Churn',axis=1)
y=df['Churn']

In [46]:
num_feat=make_column_selector(dtype_exclude=['object','category'])
cat_feat=make_column_selector(dtype_include=['object','category'])

num_pipeline=Pipeline([
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())])

cat_pipeline=Pipeline([
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('encoder',OneHotEncoder(handle_unknown='ignore', drop='first'))])

preprocessor=ColumnTransformer([
    ('num',num_pipeline,num_feat),
    ('cat',cat_pipeline,cat_feat)])

pipeline = Pipeline([
    ('preprocessing', preprocessor),
    ('model', LogisticRegression(max_iter=1000))
])

In [47]:
param_grid = {
    'model__C': [0.01, 0.1, 1, 10],
    'model__penalty': ['l1', 'l2'],
    'model__solver': ['liblinear'],
    'model__class_weight': [None, 'balanced']
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

grid = GridSearchCV(
    pipeline,
    param_grid,
    cv=cv,
    scoring='roc_auc',
    n_jobs=-1,
    verbose=2,
    error_score='raise'
)

In [48]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [49]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_grp,monthly_charge,Total_services
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,No,Month-to-month,Yes,Electronic check,29.85,29.85,1,0-1yrs,low,1
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,No,One year,No,Mailed check,56.95,1889.5,1,2-3yrs,medium,3
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0-1yrs,medium,3
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,No,One year,No,Bank transfer (automatic),42.30,1840.75,1,3-4yrs,low,3
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0-1yrs,medium,1

In [50]:
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

c:\Users\NishantHP\Desktop\MLOps project\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             error_score='raise',
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x000002B0F4573490>...
                                                                                          OneHotEncoder(drop='first',
                                                                                                        handle_unknown='ignore'))]),
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x000002B0F45C3650>)])),
                                       ('model',
                                        LogisticRegression(max_iter=1000))]),
             n_jobs=-1,
             param_grid={'model__C': [0.01, 0.1, 1, 10],
                         'model__class_weight': [None, 'balanced'],
                         'model__penalty': ['l1', 'l2'],
                         'model__solver': ['liblinear']},
             scoring='roc_auc', verbose=2)

In [51]:
print("Best Params:", grid.best_params_)
print("Best Score:", grid.best_score_)

best_model = grid.best_estimator_

Best Params: {'model__C': 1, 'model__class_weight': None, 'model__penalty': 'l2', 'model__solver': 'liblinear'}
Best Score: 0.8428743570617083

In [52]:
from sklearn.model_selection import train_test_split
data=pd.read_csv('artifacts/data_ingestion/telcom.csv')
train, test = train_test_split(data,test_size=0.2)

In [ ]:
train.shape

(5634, 21)

In [ ]:
test.shape

(1409, 21)

In [54]:
yped= grid.predict(X_test)
score=accuracy_score(Y_test,yped)
score

c:\Users\NishantHP\Desktop\MLOps project\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [15] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

0.815471965933286